Hello, I am Zhentao Wang!

title: Hi! This is Zhentao Wang's blog!
description: Currently I am learning ELEC4630 Course!❤
github_username: jph00

email:zhentao.wang@uq.net.au

titles_from_headings: Zhentao Wang's blog!
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
